"""Dialect term definitions for the Dialect Thermometer integration."""

from __future__ import annotations

DIALECTS = {
    "sortland": {
        50: "Den morgen våkner du ei",
        40: "Gloheitt",
        35: "Akomna",
        30: "Vi står han vel a'",
        25: "Det e ikkje bra førr hælsa med sånn steikvarme!",
        17: "Knaillsommar",
        12: "God høytørka",
        7: "Lunt",
        2: "Hustri",
        -2: "Lævèr",
        -6: "Vasskaildt",
        -10: "Snekjen",
        -15: "Luggføre",
        -20: "Beinkaildt",
        -25: "Svinkaildt",
        -30: "Gnaillerfrost",
        -35: "Spikkjefrost",
        -35: "Tykjekaildt",
        -999: "Den morgen våkner du ei",
    },
    "hardanger": {
        45: "So varmt ha da aldri vò",
        40: "Naoe meg!",
        35: "Jyselè varmt",
        30: "No æ da nok, eg flytte vekk",
        25: "I mòrgo vette da bergsel",
        17: "Godt arbeidsvêr",
        14: "No kraonar dei tè",
        10: "Aotekje på adle bakkar",
        4: "Graokaldt",
        0: "Fare fy svedl",
        -4: "Snèkje",
        -8: "Pao med kåtena",
        -15: "Da vette endao kaldare naor austavinden kjeme",
        -20: "Eg tykkje da æ kaldt",
        -25: "Beinkaldt, spyrù du meg",
        -30: "Gjé eg va' i eit varmare land",
        -40: "No kan du koma i prysso",
        -45: "Naoe meg! Da kan ikkje vè her",
    },
}
